"""add friend edges

Revision ID: e16fdb020aed
Revises: 2cbfa1e745fd
Create Date: 2026-03-01 16:32:29.517214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16fdb020aed'
down_revision: Union[str, None] = '2cbfa1e745fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_edges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friend_edges')
    # ### end Alembic commands ###
